---
vars:
  zfstoolbox_pwd: /root/zfstoolbox

- name: Perform base packages install
  apt:
    name:
      - python3-pip
      - python3-yaml
    state: present

- name: Install execo python package
  ansible.builtin.pip:
    name: execo

- name: Download application files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { url: https://github.com/ltaulell/zfs_toolbox/blob/master/zfstoolbox/manage_conf.py.j2, dest: '{{ zfstoolbox_pwd }}/manage_conf.py', mode: '644' }
    - { url: https://github.com/ltaulell/zfs_toolbox/blob/master/zfstoolbox/zfs_common.py, dest: '{{ zfstoolbox_pwd }}/zfs_common.py', mode: '644' }
    - { url: https://github.com/ltaulell/zfs_toolbox/blob/master/zfstoolbox/zfs_actions.py.j2, dest: '{{ zfstoolbox_pwd }}/zfs_actions.py', mode: '755' }

- name: Download default config file
  ansible.builtin.get_url:
    url: https://github.com/ltaulell/zfs_toolbox/blob/master/zfstoolbox/conf/zfs_defaults.yml.j2
    dest: "{{ zfstoolbox_pwd }}/conf/zfs_defaults.yml"
    owner: root
    group: root
    mode: '644'
