---
- name: default zfstoolbox installation path
  set_fact:
    zfstoolbox_pwd: /root/zfstoolbox
    ztb_base_url: https://raw.githubusercontent.com/ltaulell/zfs_toolbox/master/zfstoolbox

- name: Perform base packages install
  apt:
    name:
      - python3-pip
      - python3-yaml
    state: present

- name: Install execo python package
  ansible.builtin.pip:
    name: execo

- name: Create zfstoolbox directory
  file:
    path: "{{ zfstoolbox_pwd }}"
    owner: root
    group: root
    mode: '644'
    state: directory

- name: Download application files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { url: '{{ ztb_base_url }}/manage_conf.py.j2', dest: '{{ zfstoolbox_pwd }}/manage_conf.py', mode: '644' }
    - { url: '{{ ztb_base_url }}/zfs_common.py', dest: '{{ zfstoolbox_pwd }}/zfs_common.py', mode: '644' }
    - { url: '{{ ztb_base_url }}/zfs_actions.py.j2', dest: '{{ zfstoolbox_pwd }}/zfs_actions.py', mode: '755' }

- name: Create zfstoolbox config directory
  file:
    path: "{{ zfstoolbox_pwd }}/conf"
    owner: root
    group: root
    mode: '644'
    state: directory

- name: Download default config file
  ansible.builtin.get_url:
    url: '{{ ztb_base_url }}/conf/zfs_defaults.yml.j2'
    dest: "{{ zfstoolbox_pwd }}/conf/zfs_defaults.yml"
    owner: root
    group: root
    mode: '644'
